import Head from "next/head";
import About from "@/layout/About";

import Navbar from "@/components/Navbar";
import Hero from "@/layout/Hero";
import Product from "@/layout/Product";
import Benefits from "@/layout/Benefits";
import Gallery from "@/layout/Gallery";
import Testimonials from "@/layout/Testimonials";
import CTA from "@/layout/CTA";
import Blog from "@/layout/Blog";
import Footer from "@/layout/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Lush Garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Product />
      <Benefits />
      <Gallery />
      <Testimonials />
      <CTA />
      <Blog />
      <Footer />
    </>
  );
}
