import Head from "next/head";
import About from "@/pages/components/About";
import Product from "@/pages/components/Product";
import Benefits from "./components/Benefits";
import Gallery from "./components/Gallery";
import Testimonials from "./components/Testimonials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <About />
      <Product />
      <Benefits />
      <Gallery />
      <Testimonials />
    </>
  );
}
